### ISSUE TITLE
packup build indexhtml faild if 

### ISSUE THREAD

**Issue by elycheikhsmail** [kt3k/packup#38]
if have in my project
static
  media/
         audio/
              audiofile1
the command 
packup build faild
but if I create above folder structure inside dist directory ( without files ) the build succed

**Comment by kt3k** [comment]
what's the error message?

**Comment by elycheikhsmail** [comment]
Writing the assets to dist
Using "static" as static directory
Writing dist/media/lettres/1.m4a 42.47KB
error: Uncaught (in promise) NotFound: No such file or directory (os error 2), open 'dist/media/lettres/1.m4a'
    await Deno.writeFile(filename, bytes);
    ^
    at async open (deno:runtime/js/40_files.js:51:17)
    at async Object.writeFile (deno:runtime/js/40_write_file.js:62:18)
    at async build (https://deno.land/x/packup@v0.1.10/cli.ts:250:5)
    at async main (https://deno.land/x/packup@v0.1.10/cli.ts:176:5)
    at async https://deno.land/x/packup@v0.1.10/cli.ts:304:13
